### ISSUE TITLE
Improve `gerrit help`

### ISSUE THREAD

**Issue by lencioni** [sds/gerrit#1]
Currently, executing `gerrit help` just says:

```
Usage: gerrit [command]
```

It would be nice if `gerrit help` at least gave you a list of commands it knows. Bonus points for `gerrit help [command]` for more detailed help on specific commands.

**Comment by sds** [comment]
d7a18725d35de1c1df205d1e6a096a1847c7c891 added support for listing all commands when you run `gerrit help`. It is available in [0.6.0](https://rubygems.org/gems/gerrit/versions/0.6.0).
