### ISSUE TITLE
`n` for "Is this ok?" prompt is not respected

### ISSUE THREAD

**Issue by lencioni** [sds/gerrit#4]
I recently ran a `gerrit push` to a group that included a number of people. When it prompted me if this was okay, I said `n` but it pushed anyway.

```
You are adding 7 people as reviewers for this change
person.one
person.two
person.three
person.four
person.five
person.six
person.seven
Is this ok? (y/n) n
Pushing changes...
```

**Comment by sds** [comment]
Fixed in e5ea471b43da4b232299a660127eac483614bb01 and released in [0.7.1](https://github.com/sds/gerrit/releases/tag/v0.7.1)
