### ISSUE TITLE
gerrit clone should install overcommit hooks if present

### ISSUE THREAD

**Issue by tdooner** [sds/gerrit#7]
It'd be cool for the gerrit gem to autodetect an `.overcommit.yml` in the cloned repository, and automatically run `overcommit --install` if necessary.

**Comment by sds** [comment]
Great idea!

I've added support in 2e3b23b1a42d062cefe3096eb574818cedbf625a for specifying a `post_setup` option in your `~/.gerrit.yaml` so this can run any generic script you like, for example:

``` yaml
...

post_setup: ['bash', '-ec',
  'if [ -f .overcommit.yml ]; then which overcommit >/dev/null || gem install overcommit; overcommit --install; fi'

...
```

**Comment by tdooner** [comment]
Oooh fancy. :sweet_potato:
