### ISSUE TITLE
Automatically install Gerrit commit-msg hook when running clone command

### ISSUE THREAD

**Issue by sds** [sds/gerrit#9]
Not every repository necessarily needs an `.overcommit.yml` file that enables Overcommit's `GerritChangeId` hook.

When you push a commit without a change ID to Gerrit for the first time, you'll see an error message like:

```
remote: ERROR: missing Change-Id in commit message footer
remote:
remote: Hint: To automatically insert Change-Id, install the hook:
remote:   gitdir=$(git rev-parse --git-dir); scp -p -P 29418 username@gerrit-host:hooks/commit-msg ${gitdir}/hooks/
```

We should just run this for you on the initial clone so that you don't have to deal with this yourself.

Thanks to @ang and @davekincade for suggesting this enhancement.

**Comment by ambikarajput** [comment]
how do i install hook on windows machine

**Comment by ambikarajput** [comment]
i am facing same problem and not able to fix it

remote: ERROR: missing Change-Id in commit message footer
remote:
remote: Hint: To automatically insert Change-Id, install the hook:
remote:   gitdir=$(git rev-parse --git-dir); scp -p -P 29418 username@gerrit-host:hooks/commit-msg ${gitdir}/hooks/
